/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.util.GregorianCalendar;

/**
 *
 * @author Sergio Rafael
 */
public class Fecha extends javax.swing.JPanel {

    /**
     * Creates new form Fecha
     */
    public Fecha() {
        initComponents();
    }
    
    public void habilitar(boolean a){
        jSpinner1.setEnabled(a);
        jSpinner2.setEnabled(a);
        jComboBox1.setEnabled(a);
    }
    public void setYear(int year){
        jSpinner1.setValue(year);
    }
    public String getYear(){
        return jSpinner1.getValue().toString();
    }
    
    public void setDay(int Day){
        jSpinner2.setValue(Day);
    }
    
    public String getDay(){
        String a = jSpinner2.getValue().toString();
        return a.length()==1?"0"+a:a;
    }
    
    public void setMonth(int Month){
        jComboBox1.setSelectedIndex(Month);
    }
    
    public String getMonth(){
        return jComboBox1.getSelectedItem().toString();
    }
    
    public String [] getfecha(){
        String a []= {jSpinner2.getValue().toString()+" de "+jComboBox1.getSelectedItem().toString()+" de "+jSpinner1.getValue().toString(),
            jSpinner1.getValue().toString()+"-"+(jComboBox1.getSelectedIndex()+1)+"-"+jSpinner2.getValue().toString()};
    return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        jLabel1.setText("Mes:");

        jSpinner1.setValue(2000);
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jLabel2.setText("Año:");

        jLabel3.setText("Día:");

        jSpinner2.setValue(1);
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        comprovar();
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        comprovar();
    }//GEN-LAST:event_jSpinner2StateChanged

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        comprovar();
    }//GEN-LAST:event_jComboBox1ItemStateChanged
    
    private void comprovar(){
        
        int dia = Integer.parseInt(jSpinner2.getValue().toString());
        int año = Integer.parseInt(jSpinner1.getValue().toString());
        int mes = jComboBox1.getSelectedIndex();
        int i = new GregorianCalendar().getTime().getYear()+1900;
        int j = new GregorianCalendar().getTime().getDate();
        int k = new GregorianCalendar().getTime().getMonth();
        if(año > i){
            jSpinner1.setValue(i);
        }
        if(año == i && mes>k){
            jComboBox1.setSelectedIndex(k);
        }
        if(año == i && mes==k && dia > j){
            jSpinner2.setValue(j);
        }
        if(dia<1){
            jSpinner2.setValue(1);
            return;
        }
        if(año<1900){
            jSpinner1.setValue(1900);
            return;
        }
        int a = mes;
        if(a==1 && esBisiesto(año) && dia>29){
            jSpinner2.setValue(29);
            return;
        }
        if(a==1 && !esBisiesto(año) && dia>28){
            jSpinner2.setValue(28);
            return;
        }
        //0,2,4,6,7,9,11
        if((a==0 || a==2 || a==4 || a==6 || a==7 || a==9 || a==11) && dia>31){
            jSpinner2.setValue(31);
            return;
        }
        if(dia>30){
            jSpinner2.setValue(30);
            return;
        }
    }
    
    private boolean esBisiesto(int u){
        return (u%4==0 && (u%100!=0 || u%400!=0));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    // End of variables declaration//GEN-END:variables
}
